DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS itemorder;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE itemorder (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    item TEXT UNIQUE NOT NULL,
    item_description TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);
